### ISSUE TITLE
Implement "skip" and "take" parameters for GetAll methods

### ISSUE THREAD

**Issue by komalg1** [andreluizsecco/Cognitive-LUIS-Programmatic#5]
Get All Intents returning only 100 intents. How to get all the intents?

**Comment by andreluizsecco** [comment]
Reviewing the documentation, it is possible to get a list of up to 500 records per page and optionally browse the pages as well, in order to capture all the records.
Documentation: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c0d
I will add it to the backlog and it may be available in the next release.

**Comment by komalg1** [comment]
Yes I had seen the documentation and saw that it was possible with Skip and take but could not see the same in the LuisProgClient.cs file GetAllIntentsAsync method. Will wait for the next release.
Thank you for your response!

**Comment by andreluizsecco** [comment]
Closed #5 in commit f89f32c66cf9ab1a5ab66285bc02ccc0e049cc64

**Comment by andreluizsecco** [comment]
Implemented in commit f89f32c66cf9ab1a5ab66285bc02ccc0e049cc64
